# Generated by Django 3.2.7 on 2021-10-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='departure_date',
            new_name='departuredate',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='return_data',
            new_name='returndata',
        ),
    ]
