# Generated by Django 3.2.7 on 2021-10-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0002_auto_20211001_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='returndata',
            new_name='returndate',
        ),
    ]
